<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$cities = [
			["name" => "الفجيرة", "country_code" => "AE"],
			["name" => "أبو ظبي", "country_code" => "AE"],
			["name" => "دبي", "country_code" => "AE"],
			["name" => "رأس الخيمة", "country_code" => "AE"],
			["name" => "ام القيوين", "country_code" => "AE"],
			["name" => "الشارقة", "country_code" => "AE"],
			["name" => "عجمان", "country_code" => "AE"],
			["name" => "جد حفص", "country_code" => "BH"],
			["name" => "المنطقة الشمالية", "country_code" => "BH"],
			["name" => "المنامة", "country_code" => "BH"],
			["name" => "سترة", "country_code" => "BH"],
			["name" => "المنطقة الغربية", "country_code" => "BH"],
			["name" => "ولاية جزرور حوار", "country_code" => "BH"],
			["name" => "الحد", "country_code" => "BH"],
			["name" => "المنطقة الوسطى", "country_code" => "BH"],
			["name" => "الرفاع", "country_code" => "BH"],
			["name" => "مدينة", "country_code" => "BH"],
			["name" => "عين تموشنت", "country_code" => "DZ"],
			["name" => "وهران", "country_code" => "DZ"],
			["name" => "المدية", "country_code" => "DZ"],
			["name" => "الشلف", "country_code" => "DZ"],
			["name" => "بشار", "country_code" => "DZ"],
			["name" => "تمنراست", "country_code" => "DZ"],
			["name" => "بجاية", "country_code" => "DZ"],
			["name" => "تيزي وزو", "country_code" => "DZ"],
			["name" => "بومرداس", "country_code" => "DZ"],
			["name" => "عين الدفلة", "country_code" => "DZ"],
			["name" => "عنابة", "country_code" => "DZ"],
			["name" => "سطيف", "country_code" => "DZ"],
			["name" => "غليزان", "country_code" => "DZ"],
			["name" => "ماسكارا", "country_code" => "DZ"],
			["name" => "مستغانم", "country_code" => "DZ"],
			["name" => "تيارت", "country_code" => "DZ"],
			["name" => "برج بوعريريج", "country_code" => "DZ"],
			["name" => "تيبازة", "country_code" => "DZ"],
			["name" => "البويرة", "country_code" => "DZ"],
			["name" => "تيسمسيلت", "country_code" => "DZ"],
			["name" => "جيجل", "country_code" => "DZ"],
			["name" => "صيدا", "country_code" => "DZ"],
			["name" => "إليزي", "country_code" => "DZ"],
			["name" => "تلمسان", "country_code" => "DZ"],
			["name" => "أدرار", "country_code" => "DZ"],
			["name" => "الأغواط", "country_code" => "DZ"],
			["name" => "قسنطينة", "country_code" => "DZ"],
			["name" => "خنشلة", "country_code" => "DZ"],
			["name" => "باتنة", "country_code" => "DZ"],
			["name" => "الجزائر", "country_code" => "DZ"],
			["name" => "مسيلة", "country_code" => "DZ"],
			["name" => "سكيكدة", "country_code" => "DZ"],
			["name" => "ام البواقي", "country_code" => "DZ"],
			["name" => "نعمة", "country_code" => "DZ"],
			["name" => "سيدي بلعباس", "country_code" => "DZ"],
			["name" => "ميلة", "country_code" => "DZ"],
			["name" => "ورقلة", "country_code" => "DZ"],
			["name" => "الجلفة", "country_code" => "DZ"],
			["name" => "البيض", "country_code" => "DZ"],
			["name" => "سوق أهراس", "country_code" => "DZ"],
			["name" => "الواد", "country_code" => "DZ"],
			["name" => "البليدة", "country_code" => "DZ"],
			["name" => "بسكرة", "country_code" => "DZ"],
			["name" => "تبسة", "country_code" => "DZ"],
			["name" => "قالمة", "country_code" => "DZ"],
			["name" => "تندوف", "country_code" => "DZ"],
			["name" => "غرداية", "country_code" => "DZ"],
			["name" => "الشرقية", "country_code" => "EG"],
			["name" => "الغربية", "country_code" => "EG"],
			["name" => "الدقهلية", "country_code" => "EG"],
			["name" => "الجيزة", "country_code" => "EG"],
			["name" => "المنيا", "country_code" => "EG"],
			["name" => "كفر الشيخ", "country_code" => "EG"],
			["name" => "البحيرة", "country_code" => "EG"],
			["name" => "قنا", "country_code" => "EG"],
			["name" => "القاهره", "country_code" => "EG"],
			["name" => "الاسكندرية", "country_code" => "EG"],
			["name" => "الفيوم", "country_code" => "EG"],
			["name" => "أسيوط", "country_code" => "EG"],
			["name" => "المنوفية", "country_code" => "EG"],
			["name" => "بني سويف", "country_code" => "EG"],
			["name" => "القليوبية", "country_code" => "EG"],
			["name" => "أسوان", "country_code" => "EG"],
			["name" => "شمال سينا", "country_code" => "EG"],
			["name" => "سوهاج", "country_code" => "EG"],
			["name" => "جنب سينا", "country_code" => "EG"],
			["name" => "البحر الاحمر", "country_code" => "EG"],
			["name" => "الاسماعيلية", "country_code" => "EG"],
			["name" => "دمياط", "country_code" => "EG"],
			["name" => "مطروح", "country_code" => "EG"],
			["name" => "كما سوايز", "country_code" => "EG"],
			["name" => "الوادي الجديد", "country_code" => "EG"],
			["name" => "بور سعيد", "country_code" => "EG"],
			["name" => "السليمانية", "country_code" => "IQ"],
			["name" => "ذي قار", "country_code" => "IQ"],
			["name" => "ميسان", "country_code" => "IQ"],
			["name" => "ديالى", "country_code" => "IQ"],
			["name" => "بغداد", "country_code" => "IQ"],
			["name" => "أكانت", "country_code" => "IQ"],
			["name" => "صلاح الدين", "country_code" => "IQ"],
			["name" => "القادسية", "country_code" => "IQ"],
			["name" => "بابل", "country_code" => "IQ"],
			["name" => "كربلاء", "country_code" => "IQ"],
			["name" => "النجف", "country_code" => "IQ"],
			["name" => "المثنى", "country_code" => "IQ"],
			["name" => "الانبار", "country_code" => "IQ"],
			["name" => "دهوك", "country_code" => "IQ"],
			["name" => "نينوى", "country_code" => "IQ"],
			["name" => "اربيل", "country_code" => "IQ"],
			["name" => "البصرة", "country_code" => "IQ"],
			["name" => "في التميم", "country_code" => "IQ"],
			["name" => "في الطفيلة", "country_code" => "JO"],
			["name" => "الكرك", "country_code" => "JO"],
			["name" => "البلقاء", "country_code" => "JO"],
			["name" => "عمان", "country_code" => "JO"],
			["name" => "العقبة", "country_code" => "JO"],
			["name" => "الكوييت", "country_code" => "KW"],
			["name" => "الجهراء", "country_code" => "KW"],
			["name" => "شمال لبنان", "country_code" => "LB"],
			["name" => "الجنوب", "country_code" => "LB"],
			["name" => "بيروت", "country_code" => "LB"],
			["name" => "جبل لبنان", "country_code" => "LB"],
			["name" => "البقاع", "country_code" => "LB"],
			["name" => "لبنان-سود", "country_code" => "LB"],
			["name" => "يفرن", "country_code" => "LY"],
			["name" => "طرابلس", "country_code" => "LY"],
			["name" => "أحد فنادق الخمس", "country_code" => "LY"],
			["name" => "العزيزية", "country_code" => "LY"],
			["name" => "الزاوية", "country_code" => "LY"],
			["name" => "مصراتة", "country_code" => "LY"],
			["name" => "غريان", "country_code" => "LY"],
			["name" => "طبرق", "country_code" => "LY"],
			["name" => "ترهونة", "country_code" => "LY"],
			["name" => "الشطي", "country_code" => "LY"],
			["name" => "اجدابيا", "country_code" => "LY"],
			["name" => "مرزق", "country_code" => "LY"],
			["name" => "الجبل الاخضر", "country_code" => "LY"],
			["name" => "غدامس", "country_code" => "LY"],
			["name" => "Awbari", "country_code" => "LY"],
			["name" => "الخمص", "country_code" => "LY"],
			["name" => "الكفرة", "country_code" => "LY"],
			["name" => "الفاتح", "country_code" => "LY"],
			["name" => "بنغازي", "country_code" => "LY"],
			["name" => "زليتن", "country_code" => "LY"],
			["name" => "الجفرة", "country_code" => "LY"],
			["name" => "Sawfajjin", "country_code" => "LY"],
			["name" => "درنة", "country_code" => "LY"],
			["name" => "سبها", "country_code" => "LY"],
			["name" => "سرت", "country_code" => "LY"],
			["name" => "براكنة", "country_code" => "MR"],
			["name" => "هده الشوقي", "country_code" => "MR"],
			["name" => "غورغول", "country_code" => "MR"],
			["name" => "العصابة", "country_code" => "MR"],
			["name" => "جواديماكا", "country_code" => "MR"],
			["name" => "أدرار", "country_code" => "MR"],
			["name" => "حوده الغربي", "country_code" => "MR"],
			["name" => "تيرس زمور", "country_code" => "MR"],
			["name" => "إنشيري", "country_code" => "MR"],
			["name" => "ترارزة", "country_code" => "MR"],
			["name" => "داخلة نواذيبو", "country_code" => "MR"],
			["name" => "تاغانت", "country_code" => "MR"],
			["name" => "الباطنة", "country_code" => "OM"],
			["name" => "الزاهرة", "country_code" => "OM"],
			["name" => "الشرقية", "country_code" => "OM"],
			["name" => "مسقط", "country_code" => "OM"],
			["name" => "مسندم", "country_code" => "OM"],
			["name" => "ظفار", "country_code" => "OM"],
			["name" => "مكه", "country_code" => "SA"],
			["name" => "الرياض", "country_code" => "SA"],
			["name" => "وابل", "country_code" => "SA"],
			["name" => "الحدود الشمالية", "country_code" => "SA"],
			["name" => "جازان", "country_code" => "SA"],
			["name" => "الشرقية", "country_code" => "SA"],
			["name" => "المدينة", "country_code" => "SA"],
			["name" => "القاسم", "country_code" => "SA"],
			["name" => "الباحة", "country_code" => "SA"],
			["name" => "تبوك", "country_code" => "SA"],
			["name" => "الجوف", "country_code" => "SA"],
			["name" => "بحر الغزال", "country_code" => "SD"],
			["name" => "نهر النيل", "country_code" => "SD"],
			["name" => "دارفور", "country_code" => "SD"],
			["name" => "كردفان", "country_code" => "SD"],
			["name" => "الوسطى", "country_code" => "SD"],
			["name" => "الرماد الشمالي", "country_code" => "SD"],
			["name" => "الشرقية", "country_code" => "SD"],
			["name" => "الاستيوة", "country_code" => "SD"],
			["name" => "الخرطوم", "country_code" => "SD"],
			["name" => "شمال دارفور", "country_code" => "SD"],
			["name" => "ولاية وسط الاستوائية", "country_code" => "SD"],
			["name" => "ولاية الوحده", "country_code" => "SD"],
			["name" => "كسلا", "country_code" => "SD"],
			["name" => "جنوب كردفان", "country_code" => "SD"],
			["name" => "أعالي النيل", "country_code" => "SD"],
			["name" => "جنوب دارفور", "country_code" => "SD"],
			["name" => "الحسكة", "country_code" => "SY"],
			["name" => "الرقة", "country_code" => "SY"],
			["name" => "طرطوس", "country_code" => "SY"],
			["name" => "ريف دمشق", "country_code" => "SY"],
			["name" => "حمص", "country_code" => "SY"],
			["name" => "إدلب", "country_code" => "SY"],
			["name" => "حماه", "country_code" => "SY"],
			["name" => "حلب", "country_code" => "SY"],
			["name" => "القنيطرة", "country_code" => "SY"],
			["name" => "دار", "country_code" => "SY"],
			["name" => "كما السويداء", "country_code" => "SY"],
			["name" => "اللاذقية", "country_code" => "SY"],
			["name" => "دير الزور", "country_code" => "SY"],
			["name" => "دمشق", "country_code" => "SY"],
			["name" => "Madanin", "country_code" => "TN"],
			["name" => "الكاف", "country_code" => "TN"],
			["name" => "توزر", "country_code" => "TN"],
			["name" => "سوسة", "country_code" => "TN"],
			["name" => "قابس", "country_code" => "TN"],
			["name" => "صفاقس", "country_code" => "TN"],
			["name" => "بنزرت", "country_code" => "TN"],
			["name" => "المنستير", "country_code" => "TN"],
			["name" => "نابل", "country_code" => "TN"],
			["name" => "القصرين", "country_code" => "TN"],
			["name" => "تطاوين", "country_code" => "TN"],
			["name" => "سيدي بوزيد", "country_code" => "TN"],
			["name" => "المهدية", "country_code" => "TN"],
			["name" => "جندوبة", "country_code" => "TN"],
			["name" => "بن عروس", "country_code" => "TN"],
			["name" => "القيروان", "country_code" => "TN"],
			["name" => "زغوان", "country_code" => "TN"],
			["name" => "قبلي", "country_code" => "TN"],
			["name" => "باجه", "country_code" => "TN"],
			["name" => "سليانة", "country_code" => "TN"],
			["name" => "تونس", "country_code" => "TN"],
			["name" => "لحج", "country_code" => "YE"],
			["name" => "صعدة", "country_code" => "YE"],
			["name" => "الحديدة", "country_code" => "YE"],
			["name" => "مأرب", "country_code" => "YE"],
			["name" => "البيضاء", "country_code" => "YE"],
			["name" => "ذمار", "country_code" => "YE"],
			["name" => "صنعاء'", "country_code" => "YE"],
			["name" => "المهرة", "country_code" => "YE"],
			["name" => "حضرموت", "country_code" => "YE"],
			["name" => "تعز", "country_code" => "YE"],
			["name" => "حجة", "country_code" => "YE"],
			["name" => "أبين", "country_code" => "YE"],
			["name" => "إب", "country_code" => "YE"],
			["name" => "عدن", "country_code" => "YE"],
			["name" => "المحويت", "country_code" => "YE"],
			["name" => "الجوف", "country_code" => "YE"],
		];

		foreach($cities as $city) {
			City::create($city);
		}
        

	}
}
